### PR TITLE
RT-595-Medication-Order : Medication Order is inconsistent

### PR DESCRIPTION
**Pull request by yashpmohod**
## Overview
Remove reverse() from the dataset list.
Screenshot from 2023-01-25 18-34-22

## How it was tested
Ran showcase app locally.

## Checklist

- [x] The title contains a short meaningful summary
- [x] I have added a link to this PR in the Jira issue
- [x] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [x] I have run unit tests locally
- [ ] I have updated documentation (including README)

### CODE REVIEW

**Comment by semicolin** [comment]
Did you test with blood pressure layer? `dataset-list` was reversing the datasets so that blood pressure datasets would display in the correct order.

**Comment by yashpmohod** [comment]
> Did you test with blood pressure layer? `dataset-list` was reversing the datasets so that blood pressure datasets would display in the correct order.

**Comment by yashpmohod** [comment]
> Did you test with blood pressure layer? `dataset-list` was reversing the datasets so that blood pressure datasets would display in the correct order.

Okay, I will check for all layers and update PR regarding that.

**Comment by yashpmohod** [comment]
> > Did you test with blood pressure layer? `dataset-list` was reversing the datasets so that blood pressure datasets would display in the correct order.
> 
> Okay, I will check for all layers and update PR regarding that.

image
image

**Comment by semicolin** [comment]
From your screenshot, it looks like the color gradient on the summary card border is still in the wrong order.

**Comment by yashpmohod** [comment]
> From your screenshot, it looks like the color gradient on the summary card border is still in the wrong order.

okay, I will fix the border color also.

**Review by semicolin — APPROVED** [review]

**Pull request merged**
