### PR TITLE
RT-599-Adjust-color-palette

### PR DESCRIPTION
**Pull request by amolht**
## Overview
Changed the red color to light red and the yellow color to dark yellow in the color palette.

## How it was tested
Tested it by launching a showcase locally.

## Checklist

- [X] The title contains a short meaningful summary
- [X] I have added a link to this PR in the Jira issue
- [X] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [X] I have run unit tests locally
- [ ] I have updated documentation (including README)

### CODE REVIEW

**Comment by semicolin** [comment]
Please add a screenshot showing the new colors

**Comment by amolht** [comment]
> Please add a screenshot showing the new colors

image
image

**Comment by semicolin** [comment]
@amolht the colors in your screenshot don't look any different to me

**Comment by amolht** [comment]
> @amolht the colors in your screenshot don't look any different to me

image

**Pull request merged**
